// GENERATED FILE — do not edit by hand.
// Regenerate with: node scripts/generate-damage-multipliers.mjs
import { EffectKey } from "./effectKeys";
import { Nightfarer } from "../utils/Nightfarers";

export interface DamageMultiplierEntry {
  multiplier: number;
  bucket?: string;
  conditionalGroup?: string;
  nightfarer?: Nightfarer;
}

export const damageMultipliers: Partial<Record<EffectKey, DamageMultiplierEntry>> = {
  [EffectKey.improvedMeleeAttackPower]: { multiplier: 1.05, bucket: "melee" },
  [EffectKey.improvedSkillAttackPower]: { multiplier: 1.15, bucket: "weaponSkill" },
  [EffectKey.improvedInitialStandardAttack]: { multiplier: 1.15, bucket: "normalAttackFirstHit" },
  [EffectKey.improvedCriticalHits]: { multiplier: 1.17, bucket: "criticalHit" },
  [EffectKey.improvedCriticalHitsPlus1]: { multiplier: 1.24, bucket: "criticalHitPlus1" },
  [EffectKey.improvedRoarAndBreathAttacks]: { multiplier: 1.15, bucket: "roarAndBreath" },
  [EffectKey.switchingWeaponsBoostsAttackPower]: { multiplier: 1.1, conditionalGroup: "onWeaponSwitch" },
  [EffectKey.boostsAttackPowerOfAddedAffinityAttacks]: { multiplier: 1.1, conditionalGroup: "onAffinityApplied" },
  [EffectKey.takingAttacksImprovesAttackPower]: { multiplier: 1.15, conditionalGroup: "onTakingDamage" },
  [EffectKey.improvedGlintbladeSorcery]: { multiplier: 1.12, bucket: "sorcerySchool:glintblade" },
  [EffectKey.improvedStonediggerSorcery]: { multiplier: 1.12, bucket: "sorcerySchool:stonedigger" },
  [EffectKey.improvedCarianSwordSorcery]: { multiplier: 1.12, bucket: "sorcerySchool:carianSword" },
  [EffectKey.improvedInvisibilitySorcery]: { multiplier: 1.12, bucket: "sorcerySchool:invisibility" },
  [EffectKey.improvedCrystalianSorcery]: { multiplier: 1.12, bucket: "sorcerySchool:crystalian" },
  [EffectKey.improvedGravitySorcery]: { multiplier: 1.12, bucket: "sorcerySchool:gravity" },
  [EffectKey.improvedThornSorcery]: { multiplier: 1.12, bucket: "sorcerySchool:thorn" },
  [EffectKey.improvedFundamentalistIncantations]: { multiplier: 1.12, bucket: "incantationSchool:fundamentalist" },
  [EffectKey.improvedDragonCultIncantations]: { multiplier: 1.12, bucket: "incantationSchool:dragonCult" },
  [EffectKey.improvedGiantsFlameIncantations]: { multiplier: 1.12, bucket: "incantationSchool:giantsFlame" },
  [EffectKey.improvedGodslayerIncantations]: { multiplier: 1.12, bucket: "incantationSchool:godslayer" },
  [EffectKey.improvedBestialIncantations]: { multiplier: 1.12, bucket: "incantationSchool:bestial" },
  [EffectKey.improvedFrenziedFlameIncantations]: { multiplier: 1.12, bucket: "incantationSchool:frenziedFlame" },
  [EffectKey.improvedDragonCommunionIncantations]: { multiplier: 1.12, bucket: "incantationSchool:dragonCommunion" },
  [EffectKey.poisonAndRotInVicinityIncreasesAttackPower]: { multiplier: 1.12, conditionalGroup: "onNearbyStatusProc" },
  [EffectKey.ironeyeBoostsThrustingCounterattacksAfterArt]: { multiplier: 1.2, conditionalGroup: "characterExclusive", nightfarer: Nightfarer.Ironeye },
  [EffectKey.raiderDamageTakenWhileUsingCharacterSkillImprovesAttack]: { multiplier: 1.1, conditionalGroup: "onTakingDamage", nightfarer: Nightfarer.Raider },
  [EffectKey.revenantPowerUpWhileFightingAlongsideFamily]: { multiplier: 1.1, conditionalGroup: "characterExclusive", nightfarer: Nightfarer.Revenant },
  [EffectKey.recluseSufferBloodLossAndIncreaseAttackPower]: { multiplier: 1.16, conditionalGroup: "characterExclusive", nightfarer: Nightfarer.Recluse },
  [EffectKey.recluseCollectingAffinityResidueActivatesTerraMagica]: { multiplier: 1.225, conditionalGroup: "characterExclusive", nightfarer: Nightfarer.Recluse },
  [EffectKey.executorCharacterSkillBoostsAttackButDrainsHP]: { multiplier: 1.35, conditionalGroup: "characterExclusive", nightfarer: Nightfarer.Executor },
  [EffectKey.undertakerActivatingUltimateArtIncreasesAttackPower]: { multiplier: 1.18, conditionalGroup: "characterExclusive", nightfarer: Nightfarer.Undertaker },
  [EffectKey.undertakerAttackPowerIncreasedByLandingTheFinalBlowOfAChainAttack]: { multiplier: 1.16, conditionalGroup: "characterExclusive", nightfarer: Nightfarer.Undertaker },
  [EffectKey.improvedDaggerAttackPower]: { multiplier: 1.09, bucket: "weapon:dagger" },
  [EffectKey.improvedStraightSwordAttackPower]: { multiplier: 1.09, bucket: "weapon:straightSword" },
  [EffectKey.improvedGreatswordAttackPower]: { multiplier: 1.09, bucket: "weapon:greatsword" },
  [EffectKey.improvedColossalSwordAttackPower]: { multiplier: 1.09, bucket: "weapon:colossalSword" },
  [EffectKey.improvedThrustingSwordAttackPower]: { multiplier: 1.09, bucket: "weapon:thrustingSword" },
  [EffectKey.improvedHeavyThrustingSwordAttackPower]: { multiplier: 1.09, bucket: "weapon:heavyThrustingSword" },
  [EffectKey.improvedCurvedSwordAttackPower]: { multiplier: 1.09, bucket: "weapon:curvedSword" },
  [EffectKey.improvedCurvedGreatswordAttackPower]: { multiplier: 1.09, bucket: "weapon:curvedGreatsword" },
  [EffectKey.improvedKatanaAttackPower]: { multiplier: 1.09, bucket: "weapon:katana" },
  [EffectKey.improvedTwinbladeAttackPower]: { multiplier: 1.09, bucket: "weapon:twinblade" },
  [EffectKey.improvedAxeAttackPower]: { multiplier: 1.09, bucket: "weapon:axe" },
  [EffectKey.improvedGreataxeAttackPower]: { multiplier: 1.09, bucket: "weapon:greataxe" },
  [EffectKey.improvedHammerAttackPower]: { multiplier: 1.09, bucket: "weapon:hammer" },
  [EffectKey.improvedFlailAttackPower]: { multiplier: 1.09, bucket: "weapon:flail" },
  [EffectKey.improvedGreatHammerAttackPower]: { multiplier: 1.09, bucket: "weapon:greatHammer" },
  [EffectKey.improvedColossalWeaponAttackPower]: { multiplier: 1.09, bucket: "weapon:colossalWeapon" },
  [EffectKey.improvedSpearAttackPower]: { multiplier: 1.09, bucket: "weapon:spear" },
  [EffectKey.improvedGreatSpearAttackPower]: { multiplier: 1.09, bucket: "weapon:greatSpear" },
  [EffectKey.improvedHalberdAttackPower]: { multiplier: 1.09, bucket: "weapon:halberd" },
  [EffectKey.improvedReaperAttackPower]: { multiplier: 1.09, bucket: "weapon:reaper" },
  [EffectKey.improvedWhipAttackPower]: { multiplier: 1.09, bucket: "weapon:whip" },
  [EffectKey.improvedFistAttackPower]: { multiplier: 1.09, bucket: "weapon:fist" },
  [EffectKey.improvedClawAttackPower]: { multiplier: 1.09, bucket: "weapon:claw" },
  [EffectKey.improvedBowAttackPower]: { multiplier: 1.06, bucket: "weapon:bow" },
  [EffectKey.improvedAttackPowerWith3PlusDaggersEquipped]: { multiplier: 1.2, conditionalGroup: "threeOrMoreOfWeaponType" },
  [EffectKey.improvedAttackPowerWith3PlusStraightSwordsEquipped]: { multiplier: 1.2, conditionalGroup: "threeOrMoreOfWeaponType" },
  [EffectKey.improvedAttackPowerWith3PlusGreatswordsEquipped]: { multiplier: 1.2, conditionalGroup: "threeOrMoreOfWeaponType" },
  [EffectKey.improvedAttackPowerWith3PlusColossalSwordsEquipped]: { multiplier: 1.2, conditionalGroup: "threeOrMoreOfWeaponType" },
  [EffectKey.improvedAttackPowerWith3PlusThrustingSwordsEquipped]: { multiplier: 1.2, conditionalGroup: "threeOrMoreOfWeaponType" },
  [EffectKey.improvedAttackPowerWith3PlusHeavyThrustingSwordsEquipped]: { multiplier: 1.2, conditionalGroup: "threeOrMoreOfWeaponType" },
  [EffectKey.improvedAttackPowerWith3PlusCurvedSwordsEquipped]: { multiplier: 1.2, conditionalGroup: "threeOrMoreOfWeaponType" },
  [EffectKey.improvedAttackPowerWith3PlusCurvedGreatswordsEquipped]: { multiplier: 1.2, conditionalGroup: "threeOrMoreOfWeaponType" },
  [EffectKey.improvedAttackPowerWith3PlusKatanaEquipped]: { multiplier: 1.2, conditionalGroup: "threeOrMoreOfWeaponType" },
  [EffectKey.improvedAttackPowerWith3PlusTwinbladesEquipped]: { multiplier: 1.2, conditionalGroup: "threeOrMoreOfWeaponType" },
  [EffectKey.improvedAttackPowerWith3PlusAxesEquipped]: { multiplier: 1.2, conditionalGroup: "threeOrMoreOfWeaponType" },
  [EffectKey.improvedAttackPowerWith3PlusGreataxesEquipped]: { multiplier: 1.2, conditionalGroup: "threeOrMoreOfWeaponType" },
  [EffectKey.improvedAttackPowerWith3PlusHammersEquipped]: { multiplier: 1.2, conditionalGroup: "threeOrMoreOfWeaponType" },
  [EffectKey.improvedAttackPowerWith3PlusFlailsEquipped]: { multiplier: 1.2, conditionalGroup: "threeOrMoreOfWeaponType" },
  [EffectKey.improvedAttackPowerWith3PlusGreatHammersEquipped]: { multiplier: 1.2, conditionalGroup: "threeOrMoreOfWeaponType" },
  [EffectKey.improvedAttackPowerWith3PlusColossalWeaponsEquipped]: { multiplier: 1.2, conditionalGroup: "threeOrMoreOfWeaponType" },
  [EffectKey.improvedAttackPowerWith3PlusSpearsEquipped]: { multiplier: 1.2, conditionalGroup: "threeOrMoreOfWeaponType" },
  [EffectKey.improvedAttackPowerWith3PlusGreatSpearsEquipped]: { multiplier: 1.2, conditionalGroup: "threeOrMoreOfWeaponType" },
  [EffectKey.improvedAttackPowerWith3PlusHalberdsEquipped]: { multiplier: 1.2, conditionalGroup: "threeOrMoreOfWeaponType" },
  [EffectKey.improvedAttackPowerWith3PlusReapersEquipped]: { multiplier: 1.2, conditionalGroup: "threeOrMoreOfWeaponType" },
  [EffectKey.improvedAttackPowerWith3PlusWhipsEquipped]: { multiplier: 1.2, conditionalGroup: "threeOrMoreOfWeaponType" },
  [EffectKey.improvedAttackPowerWith3PlusFistsEquipped]: { multiplier: 1.2, conditionalGroup: "threeOrMoreOfWeaponType" },
  [EffectKey.improvedAttackPowerWith3PlusClawsEquipped]: { multiplier: 1.2, conditionalGroup: "threeOrMoreOfWeaponType" },
  [EffectKey.improvedAttackPowerWith3PlusBowsEquipped]: { multiplier: 1.1, conditionalGroup: "threeOrMoreOfWeaponType" },
  [EffectKey.improvedAffinityAttackPower]: { multiplier: 1.05, bucket: "affinityAttackUp" },
  [EffectKey.improvedAffinityAttackPowerPlus1]: { multiplier: 1.08, bucket: "affinityAttackUp" },
  [EffectKey.improvedAffinityAttackPowerPlus2]: { multiplier: 1.1, bucket: "affinityAttackUp" },
  [EffectKey.physicalAttackUp]: { multiplier: 1.04, bucket: "element:physical" },
  [EffectKey.physicalAttackUpPlus1]: { multiplier: 1.05, bucket: "element:physical" },
  [EffectKey.physicalAttackUpPlus2]: { multiplier: 1.06, bucket: "element:physical" },
  [EffectKey.physicalAttackUpPlus3]: { multiplier: 1.105, bucket: "element:physical" },
  [EffectKey.physicalAttackUpPlus4]: { multiplier: 1.12, bucket: "element:physical" },
  [EffectKey.magicAttackPowerUp]: { multiplier: 1.04, bucket: "element:magic" },
  [EffectKey.magicAttackPowerUpPlus1]: { multiplier: 1.05, bucket: "element:magic" },
  [EffectKey.magicAttackPowerUpPlus2]: { multiplier: 1.06, bucket: "element:magic" },
  [EffectKey.magicAttackPowerUpPlus3]: { multiplier: 1.105, bucket: "element:magic" },
  [EffectKey.magicAttackPowerUpPlus4]: { multiplier: 1.12, bucket: "element:magic" },
  [EffectKey.fireAttackPowerUp]: { multiplier: 1.04, bucket: "element:fire" },
  [EffectKey.fireAttackPowerUpPlus1]: { multiplier: 1.05, bucket: "element:fire" },
  [EffectKey.fireAttackPowerUpPlus2]: { multiplier: 1.06, bucket: "element:fire" },
  [EffectKey.fireAttackPowerUpPlus3]: { multiplier: 1.105, bucket: "element:fire" },
  [EffectKey.fireAttackPowerUpPlus4]: { multiplier: 1.12, bucket: "element:fire" },
  [EffectKey.lightningAttackPowerUp]: { multiplier: 1.04, bucket: "element:lightning" },
  [EffectKey.lightningAttackPowerUpPlus1]: { multiplier: 1.05, bucket: "element:lightning" },
  [EffectKey.lightningAttackPowerUpPlus2]: { multiplier: 1.06, bucket: "element:lightning" },
  [EffectKey.lightningAttackPowerUpPlus3]: { multiplier: 1.105, bucket: "element:lightning" },
  [EffectKey.lightningAttackPowerUpPlus4]: { multiplier: 1.12, bucket: "element:lightning" },
  [EffectKey.holyAttackPowerUp]: { multiplier: 1.04, bucket: "element:holy" },
  [EffectKey.holyAttackPowerUpPlus1]: { multiplier: 1.05, bucket: "element:holy" },
  [EffectKey.holyAttackPowerUpPlus2]: { multiplier: 1.06, bucket: "element:holy" },
  [EffectKey.holyAttackPowerUpPlus3]: { multiplier: 1.105, bucket: "element:holy" },
  [EffectKey.holyAttackPowerUpPlus4]: { multiplier: 1.12, bucket: "element:holy" },
  [EffectKey.improvedSorceries]: { multiplier: 1.05, bucket: "sorceryGeneric" },
  [EffectKey.improvedSorceriesPlus1]: { multiplier: 1.085, bucket: "sorceryGeneric" },
  [EffectKey.improvedSorceriesPlus2]: { multiplier: 1.1, bucket: "sorceryGeneric" },
  [EffectKey.improvedIncantations]: { multiplier: 1.05, bucket: "incantationGeneric" },
  [EffectKey.improvedIncantationsPlus1]: { multiplier: 1.085, bucket: "incantationGeneric" },
  [EffectKey.improvedIncantationsPlus2]: { multiplier: 1.1, bucket: "incantationGeneric" },
  [EffectKey.improvedGuardCounters]: { multiplier: 1.17, bucket: "guardCounter" },
  [EffectKey.improvedGuardCountersPlus1]: { multiplier: 1.25, bucket: "guardCounter" },
  [EffectKey.improvedGuardCountersPlus2]: { multiplier: 1.29, bucket: "guardCounter" },
  [EffectKey.attackPowerIncreasesAfterUsingGreaseItems]: { multiplier: 1.1, conditionalGroup: "onGreaseItemUse" },
  [EffectKey.physicalAttackPowerIncreasesAfterUsingGreaseItemsPlus1]: { multiplier: 1.17, conditionalGroup: "onGreaseItemUse" },
  [EffectKey.physicalAttackPowerIncreasesAfterUsingGreaseItemsPlus2]: { multiplier: 1.2, conditionalGroup: "onGreaseItemUse" },
  [EffectKey.improvedThrowingPotDamage]: { multiplier: 1.15, bucket: "thrownPot" },
  [EffectKey.improvedThrowingPotDamagePlus1]: { multiplier: 1.3, bucket: "thrownPot" },
  [EffectKey.improvedThrowingKnifeDamage]: { multiplier: 1.15, bucket: "thrownKnife" },
  [EffectKey.improvedThrowingKnifeDamagePlus1]: { multiplier: 1.3, bucket: "thrownKnife" },
  [EffectKey.improvedGlintstoneAndGravityStoneDamage]: { multiplier: 1.15, bucket: "glintstoneGravityItem" },
  [EffectKey.improvedGlintstoneAndGravityStoneDamagePlus1]: { multiplier: 1.3, bucket: "glintstoneGravityItem" },
  [EffectKey.improvedPerfumingArts]: { multiplier: 1.14, bucket: "perfumeBottle" },
  [EffectKey.improvedPerfumingArtsPlus1]: { multiplier: 1.3, bucket: "perfumeBottle" },
  [EffectKey.attackPowerUpWhenFacingPoisonAfflictedEnemy]: { multiplier: 1.1, conditionalGroup: "againstStatusAffectedEnemies" },
  [EffectKey.attackPowerUpWhenFacingPoisonAfflictedEnemyPlus1]: { multiplier: 1.16, conditionalGroup: "againstStatusAffectedEnemies" },
  [EffectKey.attackPowerUpWhenFacingPoisonAfflictedEnemyPlus2]: { multiplier: 1.2, conditionalGroup: "againstStatusAffectedEnemies" },
  [EffectKey.attackPowerUpWhenFacingScarletRotAfflictedEnemy]: { multiplier: 1.1, conditionalGroup: "againstStatusAffectedEnemies" },
  [EffectKey.attackPowerUpWhenFacingScarletRotAfflictedEnemyPlus1]: { multiplier: 1.16, conditionalGroup: "againstStatusAffectedEnemies" },
  [EffectKey.attackPowerUpWhenFacingScarletRotAfflictedEnemyPlus2]: { multiplier: 1.2, conditionalGroup: "againstStatusAffectedEnemies" },
  [EffectKey.attackPowerUpWhenFacingFrostbiteAfflictedEnemy]: { multiplier: 1.1, conditionalGroup: "againstStatusAffectedEnemies" },
  [EffectKey.attackPowerUpWhenFacingFrostbiteAfflictedEnemyPlus1]: { multiplier: 1.16, conditionalGroup: "againstStatusAffectedEnemies" },
  [EffectKey.attackPowerUpWhenFacingFrostbiteAfflictedEnemyPlus2]: { multiplier: 1.2, conditionalGroup: "againstStatusAffectedEnemies" },
  [EffectKey.sleepInVicinityImprovesAttackPower]: { multiplier: 1.12, conditionalGroup: "onNearbyStatusProc" },
  [EffectKey.sleepInVicinityImprovesAttackPowerPlus1]: { multiplier: 1.22, conditionalGroup: "onNearbyStatusProc" },
  [EffectKey.madnessInVicinityImprovesAttackPower]: { multiplier: 1.12, conditionalGroup: "onNearbyStatusProc" },
  [EffectKey.madnessInVicinityImprovesAttackPowerPlus1]: { multiplier: 1.22, conditionalGroup: "onNearbyStatusProc" },
};
