// GENERATED FILE — do not edit by hand.
// Regenerate with: node scripts/generate-damage-multipliers.mjs

export const vesselNamesJa: Record<string, string> = {
  "Wylder's Chalice": "追跡者の高杯",
  "Wylder's Goblet": "追跡者の盃",
  "Wylder's Urn": "追跡者の器",
  "Soot-Covered Wylder's Urn": "煤けた追跡者の器",
  "Sealed Wylder's Urn": "封じられた追跡者の器",
  "Decrepit Wylder's Goblet": "朽ちた追跡者の盃",
  "Forgotten Wylder's Goblet": "忘れられた追跡者の盃",
  "Giant's Cradle Grail": "巨人樹の聖杯",
  "Sacred Erdtree Grail": "黄金樹の聖杯",
  "Spirit Shelter Grail": "霊樹の聖杯",
  "Scadutree Grail": "影樹の聖杯",
  "Guardian's Chalice": "守護者の高杯",
  "Guardian's Goblet": "守護者の盃",
  "Guardian's Urn": "守護者の器",
  "Soot-Covered Guardian's Urn": "煤けた守護者の器",
  "Decrepit Guardian's Goblet": "朽ちた守護者の盃",
  "Forgotten Guardian's Goblet": "忘れられた守護者の盃",
  "Ironeye's Chalice": "鉄の目の高杯",
  "Ironeye's Goblet": "鉄の目の盃",
  "Ironeye's Urn": "鉄の目の器",
  "Soot-Covered Ironeye's Urn": "煤けた鉄の目の器",
  "Sealed Ironeye's Urn": "封じられた鉄の目の器",
  "Decrepit Ironeye's Goblet": "朽ちた鉄の目の盃",
  "Forgotten Ironeye's Goblet": "忘れられた鉄の目の盃",
  "Duchess' Chalice": "レディの高杯",
  "Duchess' Goblet": "レディの盃",
  "Duchess' Urn": "レディの器",
  "Soot-Covered Duchess' Urn": "煤けたレディの器",
  "Sealed Duchess' Urn": "封じられたレディの器",
  "Decrepit Duchess' Goblet": "朽ちたレディの盃",
  "Forgotten Duchess' Goblet": "忘れられたレディの盃",
  "Raider's Chalice": "無頼漢の高杯",
  "Raider's Goblet": "無頼漢の盃",
  "Raider's Urn": "無頼漢の器",
  "Soot-Covered Raider's Urn": "煤けた無頼漢の器",
  "Sealed Raider's Urn": "封じられた無頼漢の器",
  "Decrepit Raider's Goblet": "朽ちた無頼漢の盃",
  "Forgotten Raider's Goblet": "忘れられた無頼漢の盃",
  "Revenant's Chalice": "復讐者の高杯",
  "Revenant's Goblet": "復讐者の盃",
  "Revenant's Urn": "復讐者の器",
  "Soot-Covered Revenant's Urn": "煤けた復讐者の器",
  "Sealed Revenant's Urn": "封じられた復讐者の器",
  "Decrepit Revenant's Goblet": "朽ちた復讐者の盃",
  "Forgotten Revenant's Goblet": "忘れられた復讐者の盃",
  "Recluse's Chalice": "隠者の高杯",
  "Recluse's Goblet": "隠者の盃",
  "Recluse's Urn": "隠者の器",
  "Soot-Covered Recluse's Urn": "煤けた隠者の器",
  "Sealed Recluse's Urn": "封じられた隠者の器",
  "Decrepit Recluse's Goblet": "朽ちた隠者の盃",
  "Forgotten Recluse's Goblet": "忘れられた隠者の盃",
  "Executor's Chalice": "執行者の高杯",
  "Executor's Goblet": "執行者の盃",
  "Executor's Urn": "執行者の器",
  "Soot-Covered Executor's Urn": "煤けた執行者の器",
  "Sealed Executor's Urn": "封じられた執行者の器",
  "Decrepit Executor's Goblet": "朽ちた執行者の盃",
  "Forgotten Executor's Goblet": "忘れられた執行者の盃",
  "Scholar's Chalice": "学者の高杯",
  "Scholar's Goblet": "学者の盃",
  "Scholar's Urn": "学者の器",
  "Sealed Scholar's Urn": "封じられた学者の器",
  "Soot-Covered Scholar's Urn": "煤けた学者の器",
  "Decrepit Scholar's Goblet": "朽ちた学者の盃",
  "Forgotten Scholar's Goblet": "忘れられた学者の盃",
  "Undertaker's Chalice": "葬儀屋の高杯",
  "Undertaker's Goblet": "葬儀屋の盃",
  "Undertaker's Urn": "葬儀屋の器",
  "Sealed Undertaker's Urn": "封じられた葬儀屋の器",
  "Soot-Covered Undertaker's Urn": "煤けた葬儀屋の器",
  "Decrepit Undertaker's Goblet": "朽ちた葬儀屋の盃",
};
